name: rose_hr
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0

environment:
  sdk: ^3.8.1

dependencies:
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  envied: ^1.3.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  get_it: ^8.2.0
  go_router: ^15.1.3
  info_popup: ^4.3.2
  internet_connection_checker: ^1.0.0+1
  intl: any
  json_annotation: ^4.9.0
  json_serializable: ^6.11.1
  logger: ^2.1.0
  meta: ^1.16.0
  persistent_bottom_nav_bar_v2: ^6.1.0
  pinput: ^5.0.2
  pretty_dio_logger: ^1.4.0
  shared_preferences: ^2.5.3
  vector_graphics: ^1.1.19

dev_dependencies:
  build_runner: ^2.8.0
  envied_generator: ^1.3.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  vector_graphics_compiler: ^1.1.19
  very_good_analysis: ^9.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - path: assets/vectors/
      transformers:
        - package: vector_graphics_compiler
    - assets/rasters/

  fonts:
    - family: itfMirsalC
      fonts:
        - asset: assets/fonts/itfMirsalC.otf
          weight: 400
        - asset: assets/fonts/itfMirsalC-Light.otf
          weight: 300
        - asset: assets/fonts/itfMirsalC-Medium.otf
          weight: 500
        - asset: assets/fonts/itfMirsalC-Bold.otf
          weight: 700
        - asset: assets/fonts/itfMirsalC-Black.otf
          weight: 900

flutter_assets:
  assets_path:
    - assets/vectors/
    - assets/rasters/
  output_path: lib/common/constants
  filename: app_assets.dart
  field_prefix: null
flutter_intl:
  enabled: true
